from __future__ import annotations

from careerpilot.models import Company

# Public official career entry points. URLs are health-checked at runtime; a failed source is
# isolated and never treated as proof that a company has no open positions.
DEFAULT_COMPANIES: tuple[Company, ...] = tuple(
    Company.model_validate(item)
    for item in [
        {
            "name": "腾讯",
            "aliases": ["Tencent"],
            "homepage_url": "https://www.tencent.com/",
            "career_urls": ["https://careers.tencent.com/"],
            "industry": "互联网",
            "priority": 100,
        },
        {
            "name": "阿里巴巴",
            "aliases": ["Alibaba"],
            "homepage_url": "https://www.alibabagroup.com/",
            "career_urls": ["https://talent.alibaba.com/"],
            "industry": "电商",
            "priority": 100,
        },
        {
            "name": "字节跳动",
            "aliases": ["ByteDance"],
            "homepage_url": "https://www.bytedance.com/",
            "career_urls": ["https://jobs.bytedance.com/"],
            "industry": "互联网",
            "priority": 100,
        },
        {
            "name": "百度",
            "aliases": ["Baidu"],
            "homepage_url": "https://www.baidu.com/",
            "career_urls": ["https://talent.baidu.com/jobs/list"],
            "industry": "人工智能",
            "priority": 100,
        },
        {
            "name": "美团",
            "aliases": ["Meituan"],
            "homepage_url": "https://www.meituan.com/",
            "career_urls": ["https://zhaopin.meituan.com/"],
            "industry": "互联网",
            "priority": 95,
        },
        {
            "name": "京东",
            "aliases": ["JD.com"],
            "homepage_url": "https://www.jd.com/",
            "career_urls": ["https://zhaopin.jd.com/"],
            "industry": "电商",
            "priority": 95,
        },
        {
            "name": "网易",
            "aliases": ["NetEase"],
            "homepage_url": "https://www.163.com/",
            "career_urls": ["https://hr.163.com/"],
            "industry": "游戏",
            "priority": 95,
        },
        {
            "name": "小米",
            "aliases": ["Xiaomi"],
            "homepage_url": "https://www.mi.com/",
            "career_urls": ["https://hr.xiaomi.com/"],
            "industry": "智能硬件",
            "priority": 95,
        },
        {
            "name": "华为",
            "aliases": ["Huawei"],
            "homepage_url": "https://www.huawei.com/",
            "career_urls": ["https://career.huawei.com/"],
            "industry": "通信",
            "priority": 100,
        },
        {
            "name": "大疆",
            "aliases": ["DJI"],
            "homepage_url": "https://www.dji.com/",
            "career_urls": ["https://we.dji.com/"],
            "industry": "智能硬件",
            "priority": 90,
        },
        {
            "name": "哔哩哔哩",
            "aliases": ["Bilibili"],
            "homepage_url": "https://www.bilibili.com/",
            "career_urls": ["https://jobs.bilibili.com/"],
            "industry": "互联网",
            "priority": 85,
        },
        {
            "name": "快手",
            "aliases": ["Kuaishou"],
            "homepage_url": "https://www.kuaishou.com/",
            "career_urls": ["https://zhaopin.kuaishou.cn/"],
            "industry": "互联网",
            "priority": 90,
        },
        {
            "name": "蚂蚁集团",
            "aliases": ["Ant Group"],
            "homepage_url": "https://www.antgroup.com/",
            "career_urls": ["https://talent.antgroup.com/"],
            "industry": "金融科技",
            "priority": 95,
        },
        {
            "name": "携程",
            "aliases": ["Trip.com"],
            "homepage_url": "https://group.trip.com/",
            "career_urls": ["https://job.ctrip.com/"],
            "industry": "互联网",
            "priority": 85,
        },
        {
            "name": "滴滴",
            "aliases": ["DiDi"],
            "homepage_url": "https://www.didiglobal.com/",
            "career_urls": ["https://talent.didiglobal.com/"],
            "industry": "互联网",
            "priority": 90,
        },
        {
            "name": "联想",
            "aliases": ["Lenovo"],
            "homepage_url": "https://www.lenovo.com/",
            "career_urls": ["https://jobs.lenovo.com/"],
            "industry": "科技",
            "priority": 85,
        },
        {
            "name": "中兴通讯",
            "aliases": ["ZTE"],
            "homepage_url": "https://www.zte.com.cn/",
            "career_urls": ["https://job.zte.com.cn/"],
            "industry": "通信",
            "priority": 85,
        },
        {
            "name": "OPPO",
            "aliases": ["欧珀"],
            "homepage_url": "https://www.oppo.com/",
            "career_urls": ["https://careers.oppo.com/"],
            "industry": "智能硬件",
            "priority": 85,
        },
        {
            "name": "vivo",
            "aliases": ["维沃"],
            "homepage_url": "https://www.vivo.com/",
            "career_urls": ["https://hr.vivo.com/"],
            "industry": "智能硬件",
            "priority": 85,
        },
        {
            "name": "蔚来",
            "aliases": ["NIO"],
            "homepage_url": "https://www.nio.cn/",
            "career_urls": ["https://www.nio.cn/careers"],
            "industry": "汽车科技",
            "priority": 85,
        },
        {
            "name": "小鹏汽车",
            "aliases": ["XPeng"],
            "homepage_url": "https://www.xiaopeng.com/",
            "career_urls": ["https://job.xiaopeng.com/"],
            "industry": "汽车科技",
            "priority": 85,
        },
        {
            "name": "理想汽车",
            "aliases": ["Li Auto"],
            "homepage_url": "https://www.lixiang.com/",
            "career_urls": ["https://www.lixiang.com/careers"],
            "industry": "汽车科技",
            "priority": 85,
        },
        {
            "name": "宁德时代",
            "aliases": ["CATL"],
            "homepage_url": "https://www.catl.com/",
            "career_urls": ["https://career.catl.com/"],
            "industry": "新能源",
            "priority": 80,
        },
        {
            "name": "美的集团",
            "aliases": ["Midea"],
            "homepage_url": "https://www.midea.com/",
            "career_urls": ["https://careers.midea.com/"],
            "industry": "智能制造",
            "priority": 80,
        },
        {
            "name": "海尔",
            "aliases": ["Haier"],
            "homepage_url": "https://www.haier.com/",
            "career_urls": ["https://maker.haier.net/client/hrportal/"],
            "industry": "智能制造",
            "priority": 80,
        },
        {
            "name": "科大讯飞",
            "aliases": ["iFLYTEK"],
            "homepage_url": "https://www.iflytek.com/",
            "career_urls": ["https://hr.iflytek.com/"],
            "industry": "人工智能",
            "priority": 85,
        },
        {
            "name": "金山软件",
            "aliases": ["Kingsoft"],
            "homepage_url": "https://www.kingsoft.com/",
            "career_urls": ["https://hr.wps.cn/"],
            "industry": "软件",
            "priority": 90,
        },
        {
            "name": "招商银行",
            "aliases": ["CMB"],
            "homepage_url": "https://www.cmbchina.com/",
            "career_urls": ["https://career.cmbchina.com/"],
            "industry": "银行科技",
            "priority": 90,
        },
        {
            "name": "中国银行",
            "aliases": ["BOC"],
            "homepage_url": "https://www.boc.cn/",
            "career_urls": ["https://www.boc.cn/aboutboc/bi4/"],
            "industry": "银行科技",
            "priority": 85,
        },
        {
            "name": "工商银行",
            "aliases": ["ICBC"],
            "homepage_url": "https://www.icbc.com.cn/",
            "career_urls": ["https://job.icbc.com.cn/"],
            "industry": "银行科技",
            "priority": 85,
        },
        {
            "name": "平安集团",
            "aliases": ["Ping An"],
            "homepage_url": "https://group.pingan.com/",
            "career_urls": ["https://talent.pingan.com/"],
            "industry": "金融科技",
            "priority": 90,
        },
        {
            "name": "顺丰科技",
            "aliases": ["SF Technology"],
            "homepage_url": "https://www.sf-tech.com.cn/",
            "career_urls": ["https://hr.sf-express.com/"],
            "industry": "物流科技",
            "priority": 85,
        },
    ]
)
